### ISSUE TITLE
About New item

### ISSUE THREAD

**Issue by FonDNesses** [Fried-Rice-Lab/FriedRiceLab#13]
Hello, your work has been extremely beneficial to us. I wonder if you have plans to integrate "TLC: Improving image restoration by revisiting global information aggregation" into your project? This is also a very useful technique for super-resolution. If possible, we hope that you can integrate it into your project. Thank you.

**Comment by TIANLE233** [comment]
Hello, we are grateful for your suggestion. TLC propose a meaningful technique, which deserves our attention. We plan to integrate it into our project, which may take some time. Meanwhile, you are welcome to create new pull requests.

**Comment by FonDNesses** [comment]
> Hello, we are grateful for your suggestion. TLC propose a meaningful technique, which deserves our attention. We plan to integrate it into our project, which may take some time. Meanwhile, you are welcome to create new pull requests.

Thanks, I got it and hope to see your integration soon.
Best wishes!

**Comment by liozur** [comment]
Due to academic pressures, we may not have time to complete this one in the near future. Any PR would be welcome.
