### ISSUE TITLE
重建后图像的保存位置

### ISSUE THREAD

**Issue by rideragito** [Fried-Rice-Lab/FriedRiceLab#14]
尊敬的研究者您好，我在利用该网络进行基准数据集的测试时发现，尽管log给出了测试结果的PSNR和SSIM指标，但是我无法找到重建之后的图像放在了哪里，请问这个问题我应该怎么解决呢？

**Comment by liozur** [comment]
如果命令正确的话, 超分结果应该会保存在项目根目录下的`results`文件夹中.

如果`results`文件夹中也没有的话, 你可能是忘了指定需要保存超分结果. 请使用如下的命令再试试:
```bash
python test.py -expe_opt options/repr/ESWT/ESWT-24-6_LSR.yml -task_opt options/task/LSR_x4.yml --force_yml val:save_img=true
```

这里使用了`--force_yml val:save_img=true`以强制保存超分结果.

**Comment by rideragito** [comment]
诚心地感谢作者的回复，我已经成功地实现了图片的保存，不过其中存在一个小问题，在处理Set14数据集的时候，其中有一张bridge图片，格式与其他图片不一样，因此只有将图片剔除之后才可以处理Set14数据集，请问作者这个问题该怎么处理呢？

**Comment by liozur** [comment]
不是很清楚你指的格式不一样是啥意思哎, 是四通道吗还是什么?

**Comment by rideragito** [comment]
IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed
您好，这个是运行Set14数据集时报的错

**Comment by liozur** [comment]
这个错误太宽泛了😂, 我没法给你debug.
不过我这边是没有这个问题的, 要么你用我提供的Set14数据集再试试?

**Comment by rideragito** [comment]
没有关系，这是个小问题，暂时不会影响我的相关工作，感谢您的回复，祝您生活愉快。

**Comment by liozur** [comment]
客气了~
