### ISSUE TITLE
About Pretraining Weight, PSNR and  SSIM for x2x3

### ISSUE THREAD

**Issue by OrangeLemonade17** [Fried-Rice-Lab/FriedRiceLab#15]
Hello, your work is very helpful to us. May I ask if it is convenient for you to provide us with Pretraining Weight, PSNR and SSIM for x2x3 to help us with our research? Thank you very much for sharing!

**Comment by liozur** [comment]
Thank you for your interest in our work.
We did not train the x2 ESWT model. As for the x3 ESWT model, you can easily reproduce it using the [reproduction guidance](https://github.com/Fried-Rice-Lab/FriedRiceLab/blob/master/docs/ESWT.md) we provide.

**Comment by OrangeLemonade17** [comment]
Thank you very much for your reply and sharing!
