### ISSUE TITLE
Questions about visualization

### ISSUE THREAD

**Issue by chenzean** [Fried-Rice-Lab/FriedRiceLab#18]
The LAM results for different networks are visualized in the paper "Interpreting super-resolution net- works with local attribution maps", but I can't find the code for it? I would like to ask the author how to implement the results of this part of the visualization?

**Comment by liozur** [comment]
Hi.

This is the official repository of LAM: https://github.com/X-Lowlevel-Vision/LAM_Demo

This outstanding work was not done by us. If you have any further questions related to LAM, consider contacting its corresponding author.
