### ISSUE TITLE
About Flops

### ISSUE THREAD

**Issue by CR7forMadrid** [Fried-Rice-Lab/FriedRiceLab#19]
Hello, when I apply the Analyse integrated with your project to test my model, it prompts Cuda out of memory, but after commenting out Flops it works fine.Is there any other way to test Flops?  We noticed that your project only uses one graphics card for testing when performing analyse, what should I type on the command line if I want to use two cards to test flops?

**Comment by liozur** [comment]
We do not implement multi-card analysis method :(

But you can modify the parameter `img_size` of function `analyse_pipeline` to avoid this error~
