### ISSUE TITLE
Calling the model for inference on one image

### ISSUE THREAD

**Issue by LilyTheBear** [Fried-Rice-Lab/FriedRiceLab#20]
Hi,

From the code, it is not clear how do you call the model for inference on one image, and what data format you use. Would you mind to provide one example.

**Comment by liozur** [comment]
Making inferences on a single image is no different from making inferences on multiple images. Just put this image under a folder and treat this folder as a dataset.

As for the format of the image, both jpg and png are fine. You can refer to BasicSR's documentation to determine if more formats are supported.
