### ISSUE TITLE
LAM可视化

### ISSUE THREAD

**Issue by xiaoludiver** [Fried-Rice-Lab/FriedRiceLab#23]
您好，您的工作非常interesting，请问您的LAM可视化是如何实现呢

**Comment by liozur** [comment]
我们是对 LAM 官方的代码进行了包装, 便于使用脚本对其进行调用.

感兴趣的话, 你可以看下 README 的底部, 那里给出了 LAM 的官方仓库连接.

**Comment by xiaoludiver** [comment]
> 我们是对 LAM 官方的代码进行了包装， 便于使用脚本对其进行调用.
> 
> 感兴趣的话， 你可以看下 README 的底部， 那里给出了 LAM 的官方仓库连接.

好的   ，谢谢您
