### ISSUE TITLE
LAM

### ISSUE THREAD

**Issue by SJHunag** [Fried-Rice-Lab/FriedRiceLab#26]
I encountered this situation while doing LAM, please seek help！
![image](https://github.com/Fried-Rice-Lab/FriedRiceLab/assets/144510623/8a86fe23-bd66-4a05-97d2-4e25b8229cd1)

**Comment by liozur** [comment]
请问, 模型里是否对特征图进行了平移旋转等操作?

**Comment by SJHunag** [comment]
哥，可以私聊吗？927389247

**Comment by jnpngshiii** [comment]
不好意思, 已经毕业了. 你有啥问题你可以在这里问. 或许你可以给出有关这个问题的更详细的信息.

**Comment by SJHunag** [comment]
是这样的，我这个是SwinIR的LAM，解决不了这个问题
如果可以，您可以把那个LAM的代码发给我吗

**Comment by liozur** [comment]
我实验所使用的代码都在这个仓库里. 你换其他的模型看看呢? 看看结果是不是正常的?

**Comment by liozur** [comment]
真不行你可以去看下 NTIRE 2022/2023 的官方仓库.
