### ISSUE TITLE
预训练权重无法获取

### ISSUE THREAD

**Issue by li199603** [Fried-Rice-Lab/FriedRiceLab#28]
你好，你提供的预训练权重链接无法使用，提示access denied

**Comment by liozur** [comment]
账号🈚️了... 可能没有了吧...

**Comment by li199603** [comment]
还能提供其他下载方式吗？

**Comment by li199603** [comment]
> 账号🈚️了... 可能没有了吧...

还能提供其他下载途径吗？

**Comment by liozur** [comment]
还真没找到, 主要是毕业了就没有再管它了. 不行就重新跑一下吧, 配置文件都蛮清楚的.
