### ISSUE TITLE
Can you provide log of ESWT, I will be really appreciated that!!!

### ISSUE THREAD

**Issue by longphamkhac** [Fried-Rice-Lab/FriedRiceLab#5]

**Comment by liozur** [comment]
Hey, thank you for your interest in our work! However, I'm afraid I don't have a backup of the log file :(

**Comment by longphamkhac** [comment]
Opps, tks for brilliant works!!!

**Comment by longphamkhac** [comment]
Did you reproduce ELAN upscale x2 paper with DIV2K dataset? If yes can you share the results ?

**Comment by liozur** [comment]
We only retrained x4 upscale unofficial models for ablation studies and qualitative comparisons, so we do not have the x2 upscale model of ELAN :(

**Comment by longphamkhac** [comment]
Did the x4 upscale equals to the paper report?

**Comment by liozur** [comment]
Slightly higher than the paper report.

**Comment by liozur** [comment]
I will close this issue due to lack of activity. Please feel free to reopen it.
